import os
from dotenv import load_dotenv

load_dotenv()

AZURE_STORAGE_CONNECTION_STRING = os.getenv("AZURE_STORAGE_CONNECTION_STRING")
FORM_RECOGNIZER_ENDPOINT = os.getenv("FORM_RECOGNIZER_ENDPOINT")
FORM_RECOGNIZER_KEY = os.getenv("FORM_RECOGNIZER_KEY")
AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
AZURE_OPENAI_KEY =  os.getenv("AZURE_OPENAI_KEY")

AZURE_EMBEDDING_ENDPOINT= os.getenv("AZURE_EMBEDDING_ENDPOINT")
AZURE_EMBEDDING_KEY = os.getenv("AZURE_EMBEDDING_KEY")
EMBEDDING_DEPLOYMENT_NAME = os.getenv("EMBEDDING_DEPLOYMENT_NAME")

if not AZURE_STORAGE_CONNECTION_STRING:
    raise ValueError("❌ Missing Blob connection string in .env")
